version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: social-preview-db-local
    environment:
      MYSQL_ROOT_PASSWORD: Server123@
      MYSQL_DATABASE: social-preview
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"  # Different port to avoid conflicts
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pServer123@"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    container_name: social-preview-app-local
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/social-preview?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Server123@
    restart: unless-stopped

volumes:
  mysql_data: